version: "3.9"

services:
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"

    networks:
      crops-plus:
        ipv4_address: 172.20.0.3

  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
      "

    networks:
      crops-plus:
        ipv4_address: 172.20.0.4

volumes:
  postgres_data:

networks:
  crops-plus:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
